let gamelist = [
  {
    game_name: "리니지W",
    rank: 7,
    rank_before: 1,
    server_name: "100일 다이아",
  },
  {
    game_name: "메이플스토리",
    rank: 3,
    rank_before: 2,
    server_name: "1억 메소",
  },
  {
    game_name: "바람의나라:연",
    rank: 6,
    rank_before: 3,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "리니지2M",
    rank: 19,
    rank_before: 4,
    server_name: "1만 다이아",
  },
  {
    game_name: "리니지M",
    rank: 13,
    rank_before: 5,
    server_name: "1000일 다이아",
  },
  {
    game_name: "리니지",
    rank: 10,
    rank_before: 6,
    server_name: "100만 아데나",
  },
  {
    game_name: "던전앤파이터",
    rank: 4,
    rank_before: 7,
    server_name: "1000만 골드",
  },
  {
    game_name: "패스오브엑자일",
    rank: 12,
    rank_before: 8,
    server_name: "10일 게임머니",
  },
  {
    game_name: "월드오브워크래프트:클래식",
    rank: 22,
    rank_before: 9,
    server_name: "1000일 골드",
  },
  {
    game_name: "바람의나라",
    rank: 15,
    rank_before: 10,
    server_name: "100만 바돈",
  },
  {
    game_name: "블레이드앤소울",
    rank: 31,
    rank_before: 11,
    server_name: "1만 금",
  },
  { game_name: "아이온", rank: 9, rank_before: 12, server_name: "100만 카나" },
  {
    game_name: "마비노기",
    rank: 20,
    rank_before: 13,
    server_name: "1000만 수표",
  },
  {
    game_name: "마비노기영웅전",
    rank: 32,
    rank_before: 14,
    server_name: "1000만 골드",
  },
  {
    game_name: "리니지2",
    rank: 21,
    rank_before: 15,
    server_name: "100만 아데나",
  },
  { game_name: "거상", rank: 17, rank_before: 16, server_name: "1억 냥" },
  {
    game_name: "로스트아크",
    rank: 1,
    rank_before: 17,
    server_name: "10000일 게임머니",
  },
  {
    game_name: "에오스레드",
    rank: 30,
    rank_before: 18,
    server_name: "1만 다이아",
  },
  { game_name: "V4", rank: 29, rank_before: 19, server_name: "1000일 레드젬" },
  {
    game_name: "가디우스",
    rank: 28,
    rank_before: 20,
    server_name: "100만 게임머니",
  },
  {
    game_name: "다크에덴오리진",
    rank: 33,
    rank_before: 21,
    server_name: "10억 레이",
  },
  {
    game_name: "블레이드앤소울2",
    rank: 27,
    rank_before: 22,
    server_name: "100일 게임머니",
  },
  { game_name: "소울워커", rank: 34, rank_before: 23, server_name: "1억 제니" },
  {
    game_name: "아스텔리아",
    rank: 35,
    rank_before: 24,
    server_name: "1000만 게임머니",
  },
  {
    game_name: "언디셈버",
    rank: 14,
    rank_before: 25,
    server_name: "100일 게임머니",
  },
  {
    game_name: "엘리온",
    rank: 36,
    rank_before: 26,
    server_name: "100만 게임머니",
  },
  {
    game_name: "오딘:발할라라이징",
    rank: 2,
    rank_before: 27,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "트릭스터M",
    rank: 37,
    rank_before: 37,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "디아블로2레저렉션",
    rank: 5,
    rank_before: 29,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "메이플스토리M",
    rank: 8,
    rank_before: 30,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "서든어택",
    rank: 11,
    rank_before: 31,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "던전앤파이터모바일",
    rank: 16,
    rank_before: 32,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "피파온라인4",
    rank: 18,
    rank_before: 33,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "아스가르드",
    rank: 23,
    rank_before: 34,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "그라나도에스파다",
    rank: 24,
    rank_before: 35,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "부활얍카",
    rank: 25,
    rank_before: 36,
    server_name: "1000일 게임머니",
  },
  {
    game_name: "EGON",
    rank: 26,
    rank_before: 37,
    server_name: "1000일 게임머니",
  },
];

export default function getGameList() {
  return gamelist;
}